/obj/item/taperecorder/print_transcript()
	handle_progressive_log()
	. = ..()
	if(mytape && mytape.self_deleting)
		mytape.storedinfo.Cut()
		mytape.timestamp.Cut()

/obj/item/taperecorder/playback_memory()
	// Reset text
	handle_progressive_log()
	. = ..()
	if(mytape && mytape.self_deleting)
		mytape.storedinfo.Cut()
		mytape.timestamp.Cut()

/obj/item/taperecorder/proc/handle_progressive_log()
	if(!LAZYLEN(mytape.progressive_tape))
		return
	mytape.storedinfo.Cut()
	mytape.timestamp.Cut()
	mytape.self_deleting = TRUE

	var/entry = mytape.progressive_tape[1]
	mytape.storedinfo += entry
	mytape.progressive_tape -= entry

	if(!mytape.progressive_tape.len)
		mytape.progressive_tape = null


/obj/item/rectape
	var/self_deleting = FALSE
	var/list/progressive_tape = null


/obj/item/rectape/proc/add_custom_entry(min,sec,log)
	timestamp += (min * 60) + sec
	var/MM = min
	if(length(MM) == 1) MM = "0[min]"
	var/SS = sec
	if(length(SS) == 1) SS = "0[SS]"
	storedinfo += "\[[MM]:[SS]\] [log]"

/obj/item/rectape/proc/add_progressive(log)
	if(!progressive_tape)
		progressive_tape = list()
	progressive_tape += log

//BluesREMOVE - We hath no Anna to lore.
/*
/obj/item/rectape/anna_lore
	name = "old tape"

/obj/item/rectape/anna_lore/Initialize(mapload)
	. = ..()
	icon_state = "tape_[pick("white", "blue", "red", "yellow", "purple")]"
	switch(rand(1,19))
		if(1)
			add_custom_entry(0, 0, "Recording started.")
			add_custom_entry(0, 54, "Anna Neso says, '...This is Anna Neso--Xenoarchaeologist--though I know not why I'm... making; a point of saying that, when nobody should be hearing this log but me.'")
			add_custom_entry(1, 53, "Anna Neso says, '...There's... something down there, in the deep caves. It keeps calling to me. Begging for me. I... don't much know what it is, but... Command have been far from forthcoming with information.'")
			add_custom_entry(2, 20, "Anna Neso says, '...I stand at the precipice, now. Jagged rocks lay below.'")
			add_custom_entry(2, 31, "Anna Neso says, '...I... don't think those will prove a good spot for landing.'")
			add_custom_entry(2, 38, "Anna Neso says, '...'")
			add_custom_entry(2, 49, "Anna Neso says, 'I'll just... see if my remaining steel is enough to build over them, I s'pose.'")
			add_custom_entry(3, 13, "Anna Neso says, 'Last I was here, things went... poorly. Died. Got held in questioning for hours.'")
			add_custom_entry(3, 35, "Anna Neso says, '...They let me keep that sleeve's memories, though, at least. Silver lining, I... s'pose.'")
			add_custom_entry(3, 58, "Anna Neso says, '...Nearly wish they hadn't. That shit... sucked.'")
			add_custom_entry(4, 9, "Anna Neso says, '...But! It means I know a little more now, at least.'")
			add_custom_entry(4, 22, "Anna Neso says, 'Enough dawdling--let's see what else I can figure out.'")
			add_custom_entry(4, 30, "Anna Neso says, 'End Log 1.'")
			add_custom_entry(4, 30, "Recording stopped.")

		if(2)
			add_custom_entry(4, 31, "Recording started.")
			add_custom_entry(4, 55, "Anna Neso says, '...This place feels... more open, than last time. Less claustrophobic. Maybe that's... just the mesons, though.'")
			add_custom_entry(4, 56, "Recording stopped.")

		if(3)
			add_custom_entry(4, 57, "Recording started.")
			add_custom_entry(5, 8, "Anna Neso says, 'Pants and groans.'")
			add_custom_entry(5, 17, "Anna Neso asks, 'Hrrfh... hah... there's... fuckin' carp down here?'")
			add_custom_entry(5, 25, "Anna Neso says, '...There's carp down here. Right.'")
			add_custom_entry(5, 43, "Anna Neso says, 'I'm... injured somethin' fierce, b-but... it's dead, now. And... I've found a structure.'")
			add_custom_entry(6, 05, "Anna Neso, 'Yells in pain!'")
			add_custom_entry(6, 37, "Anna Neso says, '...Living quarters...? Not especially, ah... impressive, though. There's a bug net on a shelf, and uncomfortable-looking bed... and, ah... also, a table with a lamp.'")
			add_custom_entry(6, 55, "Anna Neso says,'...I'll leave my translocator beacon here, I think.'")
			add_custom_entry(6, 59, "Anna Neso says, 'End Log 2.'")
			add_custom_entry(6, 59, "Recording stopped.")

		if(4)
			add_custom_entry(7, 0, "Recording started.")
			add_custom_entry(7, 13, "Anna Neso says, '...RIGHT. I returned home for some, ah... medical treatment. Yes. That's what it was.'")
			add_custom_entry(7, 30, "Anna Neso says, '...BUT. Expedition shall... resume, now! End Log 3.'")
			add_custom_entry(7, 30, "Recording stopped.")

		if(5)
			add_custom_entry(7, 31, "Recording started.")
			add_custom_entry(8, 23, "Anna Neso asks, '...I've found a medical bay. Abandoned, and destroyed--rife with the flesh that I now know to indicate this is part of The Terraformer. Just what... happened, here? Who was operating this place? Us?'")
			add_custom_entry(8, 45, "Anna Neso says, 'I... hate the sounds that those sphincter-doors make. Sets me on edge. Always think something's gonna just... j-jump out at me.'")
			add_custom_entry(8, 46, "Anna Neso, 'Sighs.'")
			add_custom_entry(8, 50, "Anna Neso says, '...End Log 4.'")
			add_custom_entry(8, 50, "Recording stopped.")

		if(6)
			add_custom_entry(8, 51, "Recording started.")
			add_custom_entry(9, 9, "Anna Neso says, 'Lets out a panicked pant 'n a gasp. '...I-it... s-spoke to me, again. Closer, this time.'")
			add_custom_entry(9, 17, "Anna Neso says, 'We feel you', it said. Again and again.'")
			add_custom_entry(9, 24, "Anna Neso says, 'T-the... flesh, I mean.'")
			add_custom_entry(9, 30, "Anna Neso says, 'The walls, they--'")
			add_custom_entry(9, 38, "Anna Neso says, 'More of them. They started to grow.'")
			add_custom_entry(9, 51, "Anna Neso says, '...T-towards me, they did.'")
			add_custom_entry(9, 55, "Anna Neso says, 'To close me in.'")
			add_custom_entry(10, 12, "Anna Neso says, '...'Join us', is all the deliberation it asked prior.'")
			add_custom_entry(10, 24, "Anna Neso says, 'Lets out a sharp, weary sigh.'")
			add_custom_entry(10, 33, "Anna Neso says, '...S-shit. More of it's coming-'")
			add_custom_entry(10, 35, "Anna Neso says, 'END LOG 5.'")
			add_custom_entry(10, 36, "Recording stopped.")

		if(7)
			add_custom_entry(0, 14, "Recording started.")
			add_custom_entry(0, 19, "Anna Neso says, '...R-right, ah... this is... Anna Neso, Xenoarchaeologist, concerning a... strange GPS signal, located in the underdark.'")
			add_custom_entry(0, 30, "Anna Neso says, 'Begin... l-log... 3.'")
			add_custom_entry(1, 9, "Anna Neso says, '...It's... a corpse. Looks like that... lady in Security.'")
			add_custom_entry(1, 26, "Anna Neso says, '...Or... at least it... s-should be dead.'")
			add_custom_entry(1, 37, "Anna Neso asks, '...It's... whispering?'")
			add_custom_entry(1, 44, "Anna Neso says, '...I'll... try and... g-get... closer.'")
			add_custom_entry(2, 49, "Anna Neso says, '...R-right, ah... it's... definitely her.'")
			add_custom_entry(2, 53, "Unknown whispers, 'Help me!'")
			add_custom_entry(3, 04, "Anna Neso says, '...A-ah, uhm...'")
			add_custom_entry(3, 22, "Anna Neso says, '...They... appear to be asking for help, in case i--'")
			add_custom_entry(3, 25, "Anna Neso says, 'GAGHK-'")
			add_custom_entry(3, 32, "Anna Neso says, 'F-fuck-'")
			add_custom_entry(3, 37, "Anna Neso says, 'Fuck. Fucking... s-shit--'")
			add_custom_entry(3, 44, "Anna Neso says, 'She...'")
			add_custom_entry(3, 51, "Anna Neso says, 'E-eghk... f-fucking... bursted.'")
			add_custom_entry(3, 59, "Anna Neso says, '...Fuck. Fucking hell.'")
			add_custom_entry(4, 22, "Anna Neso says, 'Takes a shuddering, hyperventilated breath.'")
			add_custom_entry(4, 30, "Anna Neso says, '...A-ah, uhm...'")
			add_custom_entry(4, 37, "Anna Neso says, '...S-something is... writing. On the floor.'")
			add_custom_entry(4, 53, "Anna Neso stutters, 'G-G-GAG-Ghk... 'o-ours-s...''")
			add_custom_entry(5, 03, "Anna Neso says, '...S-something... is... something is WRONG.'")
			add_custom_entry(5, 12, "Anna Neso says, '...I-it's... there's... something... moving.'")
			add_custom_entry(5, 19, "Anna Neso stammers, 'In-nsid-de of-f... m-me...!'")
			add_custom_entry(5, 26, "Anna Neso says, 'Lets out a shuddering gasp.'")
			add_custom_entry(5, 40, "Anna Neso says, '...F-fuck. Sensors. Right. Sensors.'")
			add_custom_entry(5, 57, "Anna Neso stutters, '...I-I...'")
			add_custom_entry(6, 47, "Anna Neso stammers, '...S-S-s-st-t-tar-rs, it-t-t-t... it-t-t-t h-h-hur-rt-ts-s...'")
			add_custom_entry(6, 53, "Anna Neso says, '...Can't... breath...'")
			add_custom_entry(7, 12, "Anna Neso says, '...T-the... ladder. Right. Gotta... get to the... f-fuckin'...'")
			add_custom_entry(7, 23, "Anna Neso stammers, '...G-G-Gh-h-hh-hk.'")
			add_custom_entry(7, 48, "Anna Neso says, '...F-fuck. Is that... mine?'")
			add_custom_entry(7, 53, "Anna Neso says, 'We feel you... Crawling within us...'")
			add_custom_entry(7, 59, "Anna Neso, 'Yells in pain!'")
			add_custom_entry(8, 02, "Anna Neso stammers, '...G-G-g-gag-g-gh-hk-k... w-w-wh-ho...?'")
			add_custom_entry(8, 05, "Anna Neso stammers, 'Is-s t-t-that-t... m-m-me?'")
			add_custom_entry(8, 38, "Anna Neso says, '...J-just... m-make it... stop, please...'")
			add_custom_entry(8, 40, "Anna Neso says, 'We are one now.... Embrace your flesh... We speak in glorious harmony with you.. Let your meat sing with us. Sing... Sing... Forever eternal...'")
			add_custom_entry(9, 9, "Anna Neso says, '...I-I don't...'")
			add_custom_entry(9, 24, "Anna Neso says, '...It... hurts. I don't... w-want to.'")
			add_custom_entry(9, 42, "Anna Neso stutters, '...P-P-p-pl-lease, j-jus-st-t...'")
			add_custom_entry(9, 45, "Anna Neso stammers, '...A l-lit-ttl-le... f-fur-rt-t-t-th-h-her-r-r.'")
			add_custom_entry(9, 54, "Anna Neso exclaims, 'Pain brings change, as meat becomes pure... Sing with us. Sing with us!'")
			add_custom_entry(9, 58, "Anna Neso says, '...Wait, no, this is...'")
			add_custom_entry(10, 02, "Anna Neso says, 'This is the wrong way-'")
			add_custom_entry(10, 38, "Anna Neso says, 'Breathes hard, labored, and panicked... the sound of something dripping audible, echoing off the cavern walls.'")
			add_custom_entry(10, 42, "Anna Neso says, 'We will become one with them all...'")
			add_custom_entry(10, 54, "Anna Neso says, '...G-ghhk...'")
			add_custom_entry(11, 06, "Anna Neso stutters, '...W-We... w-we'l-ll-l-l-l...'")
			add_custom_entry(11, 12, "Anna Neso stammers, '...'")
			add_custom_entry(11, 20, "Anna Neso says, '...Y-yes. Of... course.'")
			add_custom_entry(11, 54, "Anna Neso stutters, '...Rig-gh-h-ht-t.'")
			add_custom_entry(12, 40, "Recording stopped.")

		if(8)
			add_custom_entry( 0, 4, "Recording started.")
			add_custom_entry( 0, 4, "Anna Neso says, '...Egh. Right.'")
			add_custom_entry( 1, 0, "Anna Neso says, 'This is Anna Neso, Xenoarchaelogist, speaking on strange happenings near the Muriki terraforming outpost on September 13th, 2569.'")
			add_custom_entry( 1, 3, "Anna Neso says, 'Log begins.'")
			add_custom_entry( 1, 48, "Anna Neso says, 'Lets out a long, breathy sigh. '...Well, ah... I... found a transcript of that tape that was lost when I... became a changeling, seemingly.''")
			add_custom_entry( 2, 50, "Anna Neso asks, '...There are copies of it spread about all outside--same as when I found a copy of one of my old tapes. This one, though... it... should be lost?'")
			add_custom_entry( 3, 21, "Anna Neso says, '...It's, ah... w-well.'")
			add_custom_entry( 3, 32, "Anna Neso says, '...The contents are... concerning, to say the least.'")
			add_custom_entry( 4, 20, "Anna Neso says, 'And... there seem t'be a number of them. Outside, and near windows.'")
			add_custom_entry( 4, 56, "Anna Neso says, 'I've... gone ahead and collected as many as I could. I'd like not t'have Security up my ass trying to investigate--least of all when I'm already dealin' with my crew records being corrupted.'")
			add_custom_entry( 5, 16, "Anna Neso says, '...In... any case. I might give telescience another shot later, perhaps.'")
			add_custom_entry( 5, 20, "Anna Neso says, 'End log.'")
			add_custom_entry( 5, 20, "Recording stopped.")

		if(9)
			add_custom_entry( 0, 9, "Recording started.")
			add_custom_entry( 0, 22, "Aiektaaknell says, 'Belches loud and long for the tape, wanting to start it off properly.'")
			add_custom_entry( 2, 37, "Recording stopped.")
			add_custom_entry( 2, 38, "Recording started.")
			add_custom_entry( 5, 26, "Anna Neso says, 'Lets out a long, protracted little whimper for her own addition to the log... hardly able to be picked up by the recorder. 'I-I...' She starts, after a couple moments of silence... though rather characteristically, she doesn't manage much more than that... trailing off back to a whimper as she fidgets about in that booze-drenched tightness.'")
			add_custom_entry( 5, 40, "Aiektaaknell asks, 'Mrrr... nothing...~?'")
			add_custom_entry( 6, 2, "Aiektaaknell says, 'A shame...~'")
			add_custom_entry( 6, 5, "Recording stopped.")
			add_custom_entry( 6, 6, "Recording started.")
			add_custom_entry( 6, 22, "Aiektaaknell says, 'Lets out a long, greedy belch, once more punctuating the recording, with the wet splat of fabric, and a long sigh.'")
			add_custom_entry( 6, 30, "Aiektaaknell says, 'Last log, Anna... eh.. Neso~ Mmm... not see more, so eager give self to better predator... No protest, no struggle.. lot blush, tail wag~ Will look good here.. forever...~ Not bother sleeve, if even find remain.. Wanted this~ Will keep skull, trophy... if other bone survive, will leave here, other can keep reminder, if sentiment~'")
			add_custom_entry( 6, 36, "Recording started.")

		if(10)
			add_custom_entry( 0, 8, "Recording started.")
			add_custom_entry( 0, 8, "Ecise Nei , 'Belches.'")
			add_custom_entry( 0, 17, "Sols Uske hisses, 'This... earpiece? It's just echoing your speak to me'")
			add_custom_entry( 0, 37, "Valinari Sandivi Gloria stammers, 'As-sk-k h-him-m wh-hat-t t-t-t-the l-l-las-s-s-st-t-t-t t-th-hin-n-ng-g h-he r-r-rememb-ber-r-r-rs-s d-d-doin-ng-g-g is-s. w-w-wh-h-hen-n h-he's don-n-n-ne dr-r-r-rink-kin-ng-g.'")
			add_custom_entry( 0, 40, "Ecise Nei chirps, 'I think it's set to Common?'")
			add_custom_entry( 0, 45, "Schale says, 'Yeah it's not configured for him'")
			add_custom_entry( 0, 46, "Ecise Nei chirps, 'Make sure the earpiece is set to Sinta'")
			add_custom_entry( 1, 21, "Ecise Nei , 'Peeps like a bird.'")
			add_custom_entry( 1, 23, "Schale asks, 'How about now?'")
			add_custom_entry( 1, 34, "Sols Uske hisses, '... I understand...'")
			add_custom_entry( 1, 37, "Schale says, 'Oh good'")
			add_custom_entry( 1, 46, "Valinari Sandivi Gloria asks, 'So what was the last thing you remember doing in our facility exactly?'")
			add_custom_entry( 1, 46, "Sols Uske hisses, 'What is this place? What have you done with me?'")
			add_custom_entry( 2, 14, "Sols Uske hisses, 'I... there was a claymore I was trying to disarm... flash of purple, then white...'")
			add_custom_entry( 2, 16, "Schale says, 'This is Outpost-21... you were found in the middle of a burned out inferno in the depths of our station.'")
			add_custom_entry( 2, 27, "Schale says, 'I pulled you out and painstakingly revived you'")
			add_custom_entry( 2, 29, "Sols Uske hisses, 'Station?'")
			add_custom_entry( 2, 47, "Sols Uske hisses, 'I... appreciate that. Are you not the ones who brought me here?'")
			add_custom_entry( 2, 59, "Schale says, 'No, we were going to ask how you got here... this is a secure facility.'")
			add_custom_entry( 3, 10, "Schale asks, '...sorry am I overstepping?'")
			add_custom_entry( 3, 12, "Valinari Sandivi Gloria , 'Prbts.'")
			add_custom_entry( 3, 14, "Sols Uske hisses, 'I woke up here...'")
			add_custom_entry( 3, 15, "Schale says, 'I'm not really.. security here'")
			add_custom_entry( 3, 15, "Valinari Sandivi Gloria says, 'It's all good-'")
			add_custom_entry( 3, 31, "Sols Uske hisses, 'What are you? All of you'")
			add_custom_entry( 3, 32, "Schale asks, 'You have an earpiece, Valinari?'")
			add_custom_entry( 3, 39, "Valinari Sandivi Gloria says, 'What's happened is you broke into our facility though, and managed to kill yourself in a phoron fire.'")
			add_custom_entry( 3, 50, "Valinari Sandivi Gloria says, 'Our lovely doctor here put you back together and we want to know why you're here.'")
			add_custom_entry( 3, 53, "Ecise Nei , 'Peeps like a bird.'")
			add_custom_entry( 4, 1, "Ecise Nei , 'Trills.'")
			add_custom_entry( 4, 27, "Sols Uske hisses, 'Again, i don't know. I thought you brought me here. Abducted from the base...'")
			add_custom_entry( 4, 39, "Schale says, 'Brain is healed up'")
			add_custom_entry( 4, 48, "Ecise Nei chirps, 'I guess I am not needed anymore now that he has the earpiece?'")
			add_custom_entry( 4, 50, "Valinari Sandivi Gloria says, 'What's the last thing you do remember then? you were dead for several hours afterall.'")
			add_custom_entry( 5, 19, "Sols Uske hisses, 'I told you. I tried to disarm a claymore. It went off from safety and it broke a wall.'")
			add_custom_entry( 5, 39, "Sols Uske hisses, 'You sounded like you knew more about it than I.'")
			add_custom_entry( 5, 39, "Valinari Sandivi Gloria says, 'I see, and that resulting explosion must've broken the tank leading to the leak and then fire.'")
			add_custom_entry( 5, 42, "Ecise Nei , 'Purrs.'")
			add_custom_entry( 5, 57, "Trashfire asks, 'Sticking around?'")
			add_custom_entry( 6, 1, "Schale says, 'Well you should stay, Trashfire.'")
			add_custom_entry( 6, 2, "Valinari Sandivi Gloria says, 'But you weren't at your base, you're at ours. disarming one of our traps planted for stowaways and intruders.'")
			add_custom_entry( 6, 3, "Calza Colfax yaps, 'How we looki8n.'")
			add_custom_entry( 6, 4, "Trashfire says, 'Yeah'")
			add_custom_entry( 6, 11, "Schale says, 'Well he's healed up nicely.'")
			add_custom_entry( 6, 14, "Calza Colfax yaps, 'Goood.'")
			add_custom_entry( 6, 20, "Schale says, 'Picture of health. Valinari's taking charge of the interview now'")
			add_custom_entry( 6, 24, "Calza Colfax yaps, 'Aight.'")
			add_custom_entry( 6, 26, "Sols Uske hisses, 'I'm just trying to survive, contact home.'")
			add_custom_entry( 6, 31, "Schale says, 'Nei got him set up with a translator earpiece'")
			add_custom_entry( 6, 34, "Sols Uske hisses, 'I don't even know what you are'")
			add_custom_entry( 6, 35, "Calza Colfax yaps, 'Helpful.'")
			add_custom_entry( 6, 37, "Ecise Nei , 'Trills.'")
			add_custom_entry( 6, 41, "Calza Colfax yaps, 'Though I would've done that sooner..'")
			add_custom_entry( 6, 48, "Valinari Sandivi Gloria asks, 'Do you even know what planet you're on?'")
			add_custom_entry( 6, 48, "Schale says, 'Yeah well...'")
			add_custom_entry( 6, 56, "Calza Colfax yaps, 'I'll continue with Keith then.'")
			add_custom_entry( 7, 9, "Schale says, 'Yeah we can FINALLY get to record reviews...'")
			add_custom_entry( 7, 19, "Calza Colfax yaps, 'For the little time we have left.'")
			add_custom_entry( 7, 22, "Valinari Sandivi Gloria says, 'Do you know how you got here exactly? you seemed to be dressed almost like me.'")
			add_custom_entry( 7, 22, "Schale says, 'Yeah...'")
			add_custom_entry( 7, 27, "Schale says, 'I'll let you and Keith run off, relax a bit'")
			add_custom_entry( 7, 33, "Calza Colfax yaps, 'Yes ma'am.'")
			add_custom_entry( 7, 34, "Keith Winters says, 'Im a picture of health, so it wont be long'")
			add_custom_entry( 7, 35, "Schale says, 'I'll just keep an eye on things'")
			add_custom_entry( 7, 38, "Schale says, 'Nei... Up to you'")
			add_custom_entry( 7, 42, "Ecise Nei , 'Peeps like a bird.'")
			add_custom_entry( 7, 46, "Schale says, 'You can stick around or head back. Doesn't matter'")
			add_custom_entry( 7, 49, "Sols Uske hisses, 'These clothes I found, reminded me of what I used to wear...'")
			add_custom_entry( 7, 58, "Sols Uske hisses, 'Woke up at this... machine'")
			add_custom_entry( 8, 1, "Sols Uske hisses, 'Don't know what it was'")
			add_custom_entry( 8, 5, "Valinari Sandivi Gloria asks, 'A veteran then? like myself?'")
			add_custom_entry( 8, 6, "Ecise Nei shrieks, 'I should probably head back. I am curious but do not wish to neglect my duties!'")
			add_custom_entry( 8, 14, "Schale says, 'Well unless someone starts dying you're fine'")
			add_custom_entry( 8, 49, "Sols Uske hisses, 'Yeah, I didn't expect to get abducted by aliens'")
			add_custom_entry( 9, 2, "Valinari Sandivi Gloria asks, 'I see, so more about this machine you woke up...?'")
			add_custom_entry( 9, 20, "Schale says, 'Frankly I'm surprised you're calling us aliens... the Unathi has been a part of the solgov alliance for a few decades now...'")
			add_custom_entry( 9, 23, "Valinari Sandivi Gloria says, 'Or rather woke up at.'")
			add_custom_entry( 9, 30, "Sols Uske hisses, 'What?'")
			add_custom_entry( 9, 41, "Sols Uske hisses, 'I... that can't be right'")
			add_custom_entry( 9, 49, "Valinari Sandivi Gloria asks, 'What year is it...?'")
			add_custom_entry( 9, 51, "Sols Uske hisses, 'It was just us and the humans'")
			add_custom_entry( 9, 55, "Trashfire says, 'Granted, I believe teshari were newly liberated from the skrell'")
			add_custom_entry( 10, 1, "Schale says, ''newely''")
			add_custom_entry( 10, 14, "Trashfire says, 'New in the grand scheme of things'")
			add_custom_entry( 10, 14, "Schale says, 'Humans and Unathi have been allies for.... quite some time.'")
			add_custom_entry( 10, 23, "Valinari Sandivi Gloria asks, 'Sols what year is it exactly?'")
			add_custom_entry( 11, 40, "Sols Uske hisses, 'I... last I recall it was the 2493'")
			add_custom_entry( 11, 49, "Ecise Nei , 'Peeps like a bird.'")
			add_custom_entry( 11, 50, "Schale says, '...hmm...'")
			add_custom_entry( 11, 56, "Trashfire says, 'Damn...'")
			add_custom_entry( 11, 58, "Schale says, 'That's uh... Hm.'")
			add_custom_entry( 11, 59, "Valinari Sandivi Gloria asks, 'Were you... cryo'd perhaps?'")
			add_custom_entry( 12, 0, "Trashfire says, 'Old code'")
			add_custom_entry( 12, 14, "Schale says, 'Not gunna lie, this one's a new one for me... miiiiight be quickly falling into Calza territory...'")
			add_custom_entry( 12, 22, "Ecise Nei chirps, 'That's... 76 years...?'")
			add_custom_entry( 12, 23, "Sols Uske hisses, 'I don't recall being put in stasis'")
			add_custom_entry( 12, 28, "Valinari Sandivi Gloria says, 'It might be.'")
			add_custom_entry( 12, 30, "Schale says, 'That's pre resleeving.'")
			add_custom_entry( 12, 53, "Schale says, 'But... that's in cloning range..'")
			add_custom_entry( 12, 55, "Valinari Sandivi Gloria says, 'The current year is 2569 though, the exact date is 2569-09-26.'")
			add_custom_entry( 13, 8, "Sols Uske hisses, 'That... no that can't be true'")
			add_custom_entry( 13, 55, "Ecise Nei chirps, 'Stay calm. Deep breaths.'")
			add_custom_entry( 14, 4, "Trashfire says, 'This may require internal affairs...'")
			add_custom_entry( 14, 6, "Sols Uske hisses, 'I... need some space... too many people'")
			add_custom_entry( 14, 9, "Valinari Sandivi Gloria says, 'It is true. call Calza in, I need to step back for a second- Trashed is up to date and I'll be close by. I just need a bit of space.'")
			add_custom_entry( 14, 14, "Ecise Nei , 'Peeps like a bird.'")
			add_custom_entry( 14, 18, "Valinari Sandivi Gloria , 'Coughs!'")
			add_custom_entry( 14, 24, "Ecise Nei chirps, 'I will leave.'")
			add_custom_entry( 14, 26, "Schale says, 'Yeah... we'll let you uh... process that for a bit'")
			add_custom_entry( 14, 33, "Valinari Sandivi Gloria asks, 'PTSD too huh?'")
			add_custom_entry( 14, 38, "Schale says, 'We'll be here... intercom behind you so just... scream if you need something'")
			add_custom_entry( 14, 55, "Sols Uske hisses, 'That's... I don't know what you mean'")
			add_custom_entry( 15, 33, "Trashfire asks, 'Ya smoke, Sols?'")
			add_custom_entry( 15, 54, "Sols Uske hisses, 'Never got into that, was bad for the job'")
			add_custom_entry( 16, 0, "Valinari Sandivi Gloria asks, 'Either way. back to the topic at hand. if you weren't cryo'd and you weren't cloned... do you recall any sort of abnormalities, time space worm holes they're called now days. anything like that?'")
			add_custom_entry( 16, 28, "Sols Uske hisses, 'I went to sleep at camp... woke up in front of a machine'")
			add_custom_entry( 16, 41, "Valinari Sandivi Gloria asks, 'Can you describe this machine?'")
			add_custom_entry( 17, 17, "Sols Uske hisses, 'It had a pod in it, not full of fluid or whatever docs put in cryos'")
			add_custom_entry( 17, 24, "Valinari Sandivi Gloria whispers, 'Can you get a picture of our auto sleever and bring it back here?'")
			add_custom_entry( 17, 36, "Trashfire whispers, 'Think they're talking cryo'")
			add_custom_entry( 17, 38, "Sols Uske hisses, 'I didn't get a good look. Everything here is weird'")
			add_custom_entry( 17, 48, "Trashfire whispers, 'I'll do both'")
			add_custom_entry( 18, 19, "Valinari Sandivi Gloria asks, 'Are you talking about the machine here? in our facility? our medical bay?'")
			add_custom_entry( 18, 29, "Sols Uske hisses, 'No, before that'")
			add_custom_entry( 18, 47, "Sols Uske hisses, 'The place barely looked like it had power'")
			add_custom_entry( 19, 19, "Trashfire says, 'Point to whichever seems familiar'")
			add_custom_entry( 19, 30, "Trashfire says, 'Sup'")
			add_custom_entry( 19, 45, "Trashfire says, 'Aight'")
			add_custom_entry( 19, 55, "Trashfire says, 'Autosleever'")
			add_custom_entry( 20, 32, "Valinari Sandivi Gloria says, 'So... it sounds like you woke up in an auto sleever outside... you, never woke up when you went to sleep.'")
			add_custom_entry( 20, 46, "Sols Uske hisses, 'But...'")
			add_custom_entry( 20, 55, "Sols Uske hisses, 'What? What do you mean by sleever?'")
			add_custom_entry( 21, 2, "Sols Uske hisses, 'You keep throwing that around'")
			add_custom_entry( 21, 20, "Valinari Sandivi Gloria asks, 'You said those cloths reminded you of what you used to wear, so you were a soldier right? camping in a hostile enviroment I take it?'")
			add_custom_entry( 21, 52, "Sols Uske hisses, 'Not directly in, we were near it'")
			add_custom_entry( 21, 53, "Valinari Sandivi Gloria says, 'We'll get to the sleever- but for now, I want to know exactly who you are and this could help us figure that out.'")
			add_custom_entry( 22, 13, "Sols Uske hisses, 'I told you my name. Sols, Sols Uske'")
			add_custom_entry( 22, 59, "Valinari Sandivi Gloria says, 'A name is a name, but there's a story behind it, that's what I want to learn... and so far the story seems to be adding up to... something grim. I believe, if what you've told us is true then you were killed by your enemy in your sleep.'")
			add_custom_entry( 23, 6, "Valinari Sandivi Gloria says, 'Sols Uske.'")
			add_custom_entry( 23, 27, "Sols Uske hisses, 'If I died then how am I here now?'")
			add_custom_entry( 24, 6, "Valinari Sandivi Gloria says, 'Now we get to the sleever... Someone must've some how gotten ahold of your remains to scan them, your mind to against all odds- and input those scans into the sleeve you woke up at. giving you a new shot at life.'")
			add_custom_entry( 24, 22, "Schale says, 'Small pinch'")
			add_custom_entry( 24, 32, "Schale says, 'And one more'")
			add_custom_entry( 24, 50, "Sols Uske hisses, 'What? People don't come back when they die'")
			add_custom_entry( 24, 52, "Schale says, 'Normal pupil response..'")
			add_custom_entry( 25, 22, "Schale says, 'Heartbeat and lungs are sounding okay...'")
			add_custom_entry( 25, 26, "Valinari Sandivi Gloria says, 'They didn't in your time. but that's what resleevers do, a body is often called a sleeve now days too even.'")
			add_custom_entry( 25, 54, "Schale asks, 'Well they must've had cloning of some kind... wasn't that a 2450 invention?'")
			add_custom_entry( 26, 11, "Schale says, 'Though, that... didn't work after death you had to do brain transplanting, and... it was a whole mess'")
			add_custom_entry( 26, 19, "Schale says, 'Real messy stuff'")
			add_custom_entry( 26, 30, "Schale says, 'Got two samples.'")
			add_custom_entry( 26, 37, "Sols Uske hisses, 'I... think I'd heard of cloning. Secret projects and plans'")
			add_custom_entry( 26, 41, "Schale says, 'I'll need forensics to run a hash of it'")
			add_custom_entry( 26, 50, "Sols Uske hisses, 'Intel we learned on both ends'")
			add_custom_entry( 26, 56, "Valinari Sandivi Gloria asks, 'Do you think it's possible you were an unknowing subject in an experiment?'")
			add_custom_entry( 27, 13, "Schale says, 'Don't mind the label, I reused it'")
			add_custom_entry( 7, 19, "Trashfire says, 'No worries'")
			add_custom_entry( 27, 21, "Schale says, 'Sterilized, of course'")
			add_custom_entry( 27, 27, "Sols Uske hisses, 'I... don't know. I don't recall ever being used for that'")
			add_custom_entry( 27, 33, "Schale says, 'Wouldn't need to'")
			add_custom_entry( 27, 38, "Schale says, 'Cloning just needed a blood sample.'")
			add_custom_entry( 28, 15, "Sols Uske hisses, 'Then I wouldn't know. Last I recall I was sleeping at camp.'")
			add_custom_entry( 28, 39, "Sols Uske roars, 'You're telling me I died and woke up a century later here of all places?!'")
			add_custom_entry( 28, 39, "Valinari Sandivi Gloria says, 'Sleeping at camp over a hundred years ago if you're being truthful with us.'")
			add_custom_entry( 29, 2, "Sols Uske hisses, 'You're making as much sense to me as I am to you, buud'")
			add_custom_entry( 30, 5, "Valinari Sandivi Gloria says, 'Mmmm. your story checks out so far though... and if you were an infiltrator with hostile intent I imagine who ever sent you here of all places would've given you more than some rusty tools.'")
			add_custom_entry( 30, 26, "Sols Uske hisses, 'Those tools I'd found'")
			add_custom_entry( 31, 1, "Schale says, 'Well... I'm not exactly sure why or how you ended up here...'")
			add_custom_entry( 31, 22, "Schale says, 'This planet was an uninhabitable dirtball up until five or six years ago.'")
			add_custom_entry( 31, 47, "Schale says, 'Unless you got put into a stasis cage in your sleep and got sent to the most backwater place for.... no reason'")
			add_custom_entry( 32, 2, "Sols Uske , 'Sighs.'")
			add_custom_entry( 32, 19, "Sols Uske hisses, 'The red one mentioned I fell out of an 'Auto sleever''")
			add_custom_entry( 32, 39, "Schale says, 'Could have.'")
			add_custom_entry( 32, 45, "Schale says, 'I.. don't know exactly where you came from.'")
			add_custom_entry( 32, 56, "Valinari Sandivi Gloria says, 'We just need to figure out how exactly your scans got into an abandoned sleever...'")
			add_custom_entry( 33, 7, "Sols Uske hisses, 'Whatever machine it was looks a lot like this photo'")
			add_custom_entry( 33, 18, "Schale says, 'Oh... yeah that's an autosleever'")
			add_custom_entry( 33, 50, "Schale says, 'Well... Trashfire is contacting central... they'll send a message to the Unathi Systems, and see if they can't come pick you up'")
			add_custom_entry( 34, 8, "Schale says, 'You'll probably be detained until then'")
			add_custom_entry( 34, 9, "Sols Uske hisses, '... Understood'")
			add_custom_entry( 34, 10, "Valinari Sandivi Gloria says, 'From what I can gather Schale, he was going to sleep near an enemy position as an Unathi soldier, he was killed in his sleep and some how his mind and body scans got into that sleever. IF he's being truthful.'")
			add_custom_entry( 34, 22, "Schale says, 'How is the question...'")
			add_custom_entry( 34, 24, "Schale says, 'I mean.'")
			add_custom_entry( 34, 30, "Schale says, 'To be fair, this is the fucking planet of ghost clowns.'")
			add_custom_entry( 34, 38, "Schale says, 'So it's not like it's out of the realm of possibility'")
			add_custom_entry( 34, 57, "Schale says, 'This planet could have just.... picked him up and decided his ghost would be funny to reincarnate...'")
			add_custom_entry( 35, 4, "Schale says, 'I'd believe that crap at this point...'")
			add_custom_entry( 35, 9, "Valinari Sandivi Gloria says, 'Shit that's right- place is haunted.'")
			add_custom_entry( 35, 16, "Schale says, 'Place is haunted as fuck'")
			add_custom_entry( 35, 29, "Schale says, 'Most haunted planet in solgov space....'")
			add_custom_entry( 35, 36, "Valinari Sandivi Gloria , 'Snaps her fingers.'")
			add_custom_entry( 35, 43, "Schale says, 'Fourth most haunted planet in all of known space...'")
			add_custom_entry( 35, 56, "Valinari Sandivi Gloria says, 'Forget who it was, pretty tesh girl, mechanical limbs, got ate by critter. saw her ghost around for a bit. till we resleeved her.'")
			add_custom_entry( 35, 58, "Sols Uske hisses, 'Somehow it's not any of the wargrounds'")
			add_custom_entry( 36, 8, "Schale says, 'Yeah that happens...'")
			add_custom_entry( 36, 55, "Schale says, 'We could probably take off the straight jacket and just stick with cuffs...'")
			add_custom_entry( 36, 57, "Schale says, 'OH CRUD'")
			add_custom_entry( 37, 1, "Valinari Sandivi Gloria asks, 'Oh?'")
			add_custom_entry( 37, 2, "The Security Processing's bell rings.")
			add_custom_entry( 37, 5, "Schale says, 'His clothes'")
			add_custom_entry( 37, 35, "Valinari Sandivi Gloria says, 'Right, she's getting your cloths... don't worry we washed the hazards that killed you- again- off.'")
			add_custom_entry( 37, 47, "Sols Uske hisses, 'Substance?'")
			add_custom_entry( 37, 56, "Valinari Sandivi Gloria says, 'Phoron I believe they said.'")
			add_custom_entry( 38, 14, "Sols Uske hisses, 'Well I much appreciate being clothed'")
			add_custom_entry( 38, 34, "Valinari Sandivi Gloria says, 'Understandable.'")
			add_custom_entry( 38, 56, "You hear metal clanking.")
			add_custom_entry( 39, 9, "You hear metal clanking.")
			add_custom_entry( 39, 27, "Recording stopped.")
			add_custom_entry( 39, 28, "Recording started.")
			add_custom_entry( 39, 30, "Schale says, 'Probably a bit more comfortable'")
			add_custom_entry( 39, 35, "Sols Uske hisses, 'More burnt than I remember, but yes'")
			add_custom_entry( 39, 50, "Schale says, 'Well yes, it came out of a phoron fire... but they've been washed and cleaned as best as possible'")
			add_custom_entry( 39, 51, "Trashfire says, 'At least freshly cleaned'")
			add_custom_entry( 40, 34, "Valinari Sandivi Gloria says, 'From what we can gather Trashed, if they're being truthful they went to sleep near an enemy position, setting up camp. got killed in their sleep and woke up in an auto sleever here, a hundred years after their death. they're a soldier.'")
			add_custom_entry( 40, 55, "Valinari Sandivi Gloria says, 'Go on'")
			add_custom_entry( 42, 5, "Valinari Sandivi Gloria says, 'One moment.'")
			add_custom_entry( 43, 3, "Trashfire , 'Sighs.'")
			add_custom_entry( 43, 10, "Schale says, '...speaking of ghost clowns'")
			add_custom_entry( 43, 31, "Sols Uske hisses, 'I heard clowns before'")
			add_custom_entry( 43, 38, "Sols Uske hisses, 'Didn't know if I was hallucinating or not'")
			add_custom_entry( 43, 39, "Recording stopped.")

		if(11)
			add_custom_entry( 0, 32, "Recording started.")
			add_custom_entry( 0, 40, "Anna Neso says, '...Right. This is... Anna Neso, Xenoarchaeologist on Outpost 21. Date is 2569-10-17.'")
			add_custom_entry( 1, 11, "Anna Neso says, '...Director's sent me out to the yard, today--much as I loathe the place. No cargo, so... my bomb-making expertise is needed 'fer sourcing materials.'")
			add_custom_entry( 1, 34, "Anna Neso says, '...Detonations are already done with, mind you! There's just... a bit of an oddity, with them.'")
			add_custom_entry( 1, 57, "Anna Neso says, 'Asteroid I blew has a core of sheer, black rock. It... didn't yield under the explosions one bit.'")
			add_custom_entry( 3, 1, "Anna Neso asks, '...Likely not anomalous! But... nonetheless, I've retrieved a drill. I'm going to see if I can find a way around it all. Looks like... basalt, I think?'")
			add_custom_entry( 3, 2, "Recording stopped.")
			add_custom_entry( 3, 3, "Recording started.")
			add_custom_entry( 3, 28, "Anna Neso yells, '...Ah. There we are. Looks like my bomb was actually just a meter away from uncovering the entrance on its own!'")
			add_custom_entry( 3, 55, "Anna Neso says, '...There's a forking path, looks like. Hmm.'")
			add_custom_entry( 3, 55, "Recording stopped.")
			add_custom_entry( 3, 56, "Recording started.")
			add_custom_entry( 3, 58, "Anna Neso says, '...Ah--'")
			add_custom_entry( 4, 8, "Anna Neso says, 'A flashlight...? I didn't bring that in, myself.'")
			add_custom_entry( 4, 17, "Anna Neso says, '...I, ah...'")
			add_custom_entry( 4, 34, "Anna Neso says, '...Right. I've... brought a gun, for once, if worse comes to worst, I suppose.'")
			add_custom_entry( 5, 31, "Anna Neso says, '...A knife's blade? It's... sitting in a dead end.'")
			add_custom_entry( 6, 35, "Anna Neso says, 'A... set of prescription meson goggles. Still functional. Unfortunately, I... can't quite take off my helmet, to put them on.'")
			add_custom_entry( 7, 31, "Recording stopped.")
			add_custom_entry( 7, 32, "Recording started.")
			add_custom_entry( 7, 44, "Anna Neso says, '...I have found a stash of weapons inside, at the end of one of the tunnels.'")
			add_custom_entry( 7, 44, "Recording stopped.")

		if(12)
			add_custom_entry( 1, 4, "Recording started.")
			add_custom_entry( 1, 6, "Anna Neso says, '...Right. This is Anna Neso, Xenoarchaeologist. The date is 2569-10-17. Begin log.'")
			add_custom_entry( 2, 37, "Anna Neso says, '...I've... found an entrance to the Underdark, through the mouse-tunnels in the station's walls. It's... a terribly steep incline, but... still walkable. Even if you do manage to slip, at least, it's a tight enough fit you'll be able to catch yourself.'")
			add_custom_entry( 3, 14, "Anna Neso says, '...I've prepared a weapon I found in the yard, for a change. A phoron bomb as well, in case things get... especially bad.'")
			add_custom_entry( 3, 24, "Anna Neso says, '...Log will resume on-site.'")
			add_custom_entry( 3, 25, "Recording stopped.")
			add_custom_entry( 3, 26, "Recording started.")
			add_custom_entry( 3, 32, "Anna Neso says, '...I've arrived, and...'")
			add_custom_entry( 3, 42, "Anna Neso says, 'This isn't at all where the tunnel led, last time.'")
			add_custom_entry( 3, 56, "Anna Neso asks, '...This looks like... a surgical room?'")
			add_custom_entry( 4, 00, "Anna Neso says, 'Or--'")
			add_custom_entry( 4, 22, "Anna Neso says, 'No, not surgical. But... an emergency substation. There are cryostorage units, as well. One of the walls is built of durasteel.'")
			add_custom_entry( 5, 0, "Recording stopped.")

		if(13)
			add_custom_entry( 5, 1, "Recording started.")
			add_custom_entry( 5, 18, "Anna Neso says, '...Dormitories adjacent to it all, looks like. In an absolutely decrepit state, though.'")
			add_custom_entry( 6, 10, "Anna Neso says, '...Power seems... functional, here, oddly enough.'")
			add_custom_entry( 6, 24, "Anna Neso says, 'There's a working scrubber, there. The cryogenic oversight console was in working order, as well.'")
			add_custom_entry( 6, 33, "Anna Neso asks, '...Is there... a generator running, maybe?'")
			add_custom_entry( 7, 07, "Anna Neso says, 'I've located an access-locked door.'")
			add_custom_entry( 7, 14, "Anna Neso says, 'Attempting to hack, now.'")
			add_custom_entry( 7, 35, "Anna Neso says, '...Right. Pink wire is for bolts...'")
			add_custom_entry( 7, 50, "Anna Neso says, '...And purple controls the power.'")
			add_custom_entry( 8, 14, "Anna Neso says, 'There we are. Entry.'")
			add_custom_entry( 8, 17, "Anna Neso says, '...'")
			add_custom_entry( 8, 20, "Anna Neso says, '...It's a restroom.'")
			add_custom_entry( 8, 27, "CLUNK!")
			add_custom_entry( 8, 33, "Anna Neso says, 'AGHK-'")
			add_custom_entry( 8, 35, "Anna Neso says, 'MOTHER OF--'")
			add_custom_entry( 8, 40, "Anna Neso says, 'WHY WAS THERE A--'")
			add_custom_entry( 8, 44, "Anna Neso exclaims, 'Groans!'")
			add_custom_entry( 8, 49, "Anna Neso says, '...Of all things...'")
			add_custom_entry( 9, 1, "Anna Neso says, 'The fucking toilet was booby-trapped with a flashbang grenade.'")
			add_custom_entry( 9, 22, "Anna Neso says, '...Right. Eghk. Gotta be... cautious of those, going forward, I s'pose.'")
			add_custom_entry( 9, 35, "Anna Neso says, '...Nothing else of note, in here.'")
			add_custom_entry( 10, 7, "Anna Neso says, '...Ah. I've found...'")
			add_custom_entry( 10, 11, "Anna Neso asks, '...Soup.......?'")
			add_custom_entry( 10, 32, "Anna Neso says, '...It contains... cream of mushroom, milk, and rice.'")
			add_custom_entry( 10, 42, "Anna Neso asks, '...That doesn't sound bad, actually, necessarily?'")
			add_custom_entry( 10, 55, "Anna Neso says, '...Still unlikely I'll be trying it, given the nature of this place.'")
			add_custom_entry( 11, 32, "Anna Neso asks, '...Does that ever actually work?'")
			add_custom_entry( 11, 39, "Anna Neso says, '...RIGHT. Aghk.'")
			add_custom_entry( 12, 12, "Anna Neso says, 'I've found... a transmitter? Bluespace inhibitor next to it, as well.'")
			add_custom_entry( 12, 37, "Anna Neso says, '...I think... I'm adjacent to the terraformer, if the... sounds are anything to go off of.'")
			add_custom_entry( 12, 46, "Anna Neso says, 'Shudders.'")
			add_custom_entry( 13, 4, "Anna Neso asks, '...I wonder what would happen if I...?'")
			add_custom_entry( 13, 31, "Anna Neso says, '...Oh, wait. The monitor is displaying a message, actually.'")
			add_custom_entry( 13, 42, "Anna Neso says, '...'THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.''")
			add_custom_entry( 13, 45, "Anna Neso says, '...Hmm.'")
			add_custom_entry( 14, 5, "Anna Neso says, '...Multitool won't allow me to write my own, alas.'")
			add_custom_entry( 14, 6, "Anna Neso, 'Snorts!'")
			add_custom_entry( 14, 12, "Anna Neso asks, '...Was that blood there, before?'")
			add_custom_entry( 14, 22, "Anna Neso says, '...RIGHT. Right, ah... probably best keep moving.'")
			add_custom_entry( 14, 37, "Anna Neso says, '...Oh. What's this?'")
			add_custom_entry( 15, 4, "Anna Neso says, '...Hmm. Well... none of my tools can interface with it, at the least.'")
			add_custom_entry( 15, 53, "Anna Neso says, 'It's... some kinda machine, though? Set up next to a radio. Has an odd... 3D prism kinda shape to it. Turquoise center, with a darker metal making up the outer casing.'")
			add_custom_entry( 16, 11, "Anna Neso says, '...Oh. There's a notice board just outside that I never checked.'")
			add_custom_entry( 16, 58, "Anna Neso asks, '...Oh. These are... drawings?'")
			add_custom_entry( 17, 39, "Anna Neso says, '...There's... some kinda critter in all of 'em, often accompanied by...'")
			add_custom_entry( 18, 8, "Anna Neso asks, '...Oh. WAIT A MINUTE. Are these th'symbols that someone's been graffiti'ing all about the maintenance tunnels?'")
			add_custom_entry( 18, 21, "Anna Neso shouts, 'It looks to be a guide for interpreting them!'")
			add_custom_entry( 18, 40, "Anna Neso says, 'Right, ah... hmm. Okay. This is... helpful, actually.'")
			add_custom_entry( 19, 20, "Anna Neso says, '...RIGHT. Okay. So, then...'")
			add_custom_entry( 19, 42, "Anna Neso says, '...An X on the floor would appear to indicate... a trap? Or just... danger, in some variety.'")
			add_custom_entry( 19, 57, "Anna Neso asks, '...An arrow represents... a false wall?'")
			add_custom_entry( 20, 34, "Anna Neso says, '...They... seem to suggest the borgs are... dangerous. Presumably a stowaway, then.'")
			add_custom_entry( 20, 45, "Anna Neso says, 'And...'")
			add_custom_entry( 20, 48, "Anna Neso says, 'A-ah...'")
			add_custom_entry( 21, 20, "Anna Neso says, '...I'm... not... certain what this one is about, but it's... quite offputting. It's, ah...'")
			add_custom_entry( 21, 22, "Anna Neso says, '...'")
			add_custom_entry( 21, 34, "Anna Neso asks, '...Didn't I pass by a symbol like that on my way in here...?'")
			add_custom_entry( 21, 44, "Anna Neso says, 'Clears her throat uncomfortably.'")
			add_custom_entry( 21, 54, "Anna Neso says, '...Right, I'll... check in a minute.'")
			add_custom_entry( 22, 1, "Anna Neso says, '...More drawings to note down.'")
			add_custom_entry( 22, 22, "Anna Neso asks, '...A happy face would seem to suggest... somewhere safe? A place t'sleep?'")
			add_custom_entry( 22, 34, "Anna Neso says, 'And... the last is...'")
			add_custom_entry( 22, 37, "Anna Neso says, '...Ah.'")
			add_custom_entry( 23, 05, "Anna Neso says, 'Right. I see what that means. They're suggesting to ring the doorbells on maintenance doors before entering, so you can make sure they aren't shocked.'")
			add_custom_entry( 23, 14, "Anna Neso says, '...Right. Right! That's... all of them, then, I think.'")
			add_custom_entry( 23, 31, "Anna Neso says, '...Time to see if anything is around... the face.'")
			add_custom_entry( 24, 26, "Anna Neso says, '...Right. Ah... yes. There it is. Just... sitting in a dorm-room. A dorm-room I now realize is splattered with... a few spots of wet blood.'")
			add_custom_entry( 25, 1, "Anna Neso asks, '...There's a mattress on the other end. No bedsheet or anything. It looks... stained. Sweat, I'd think...?'")
			add_custom_entry( 25, 33, "Anna Neso asks, '...The room appears... normal?'")
			add_custom_entry( 25, 54, "Anna Neso says, '...Now that I... think about it, though...'")
			add_custom_entry( 26, 25, "Anna Neso asks, '...Why do they need to mark out safe places 'fer sleep, in specific...?'")
			add_custom_entry( 26, 31, "Anna Neso asks, 'Is it... the bed, maybe?'")
			add_custom_entry( 27, 31, "Anna Neso says, '...Maybe I'll... try resting, for a moment, here. Just to... confirm.'")
			add_custom_entry( 27, 58, "Anna Neso says, '...With my voidsuit still on, mind you--I do not want whatever +disease+ has seeped in there.'")
			add_custom_entry( 28, 16, "You hear metal clanking.")
			add_custom_entry( 29, 11, "Anna Neso says, '...Eghk. I... I am fuckin' tired, after all the... bombs, today. Don't usually make this many.'")
			add_custom_entry( 29, 20, "Anna Neso says, '...Can't hurt to rest my eyes, a moment.'")
			add_custom_entry( 31, 14, "You hear metal clanking.")
			add_custom_entry( 31, 20, "Anna Neso exclaims, 'Rouses with a snort!'")
			add_custom_entry( 31, 23, "Anna Neso says, 'GAH, fuck--'")
			add_custom_entry( 31, 25, "Anna Neso says, 'Right--'")
			add_custom_entry( 31, 27, "Anna Neso says, 'Okay, ah...'")
			add_custom_entry( 31, 38, "Anna Neso says, '...Nodded off, for a little, I think.'")
			add_custom_entry( 31, 43, "Anna Neso says, '...Not an ideal place for that.'")
			add_custom_entry( 31, 49, "Anna Neso asks, '...I... seem fine enough, though?'")
			add_custom_entry( 31, 54, "Anna Neso says, '...Hmm.'")
			add_custom_entry( 32, 30, "Anna Neso asks, '...Candles around here are still lit, I'm realizing. Someone's been living here, haven't they...?'")
			add_custom_entry( 33, 1, "Anna Neso asks, '...Right. This is... an atmospherics room?'")
			add_custom_entry( 33, 13, "Anna Neso says, '...Environmental regulation system in working order, as well.'")
			add_custom_entry( 33, 27, "Anna Neso asks, 'And... a ladder... downward...?'")
			add_custom_entry( 33, 36, "Anna Neso says, '...This is already all th'way down in the underdark.'")
			add_custom_entry( 33, 52, "Anna Neso says, '...It's... surrounded by X-marks, and... two of the faces.'")
			add_custom_entry( 33, 55, "Anna Neso says, '...'")
			add_custom_entry( 34, 4, "Anna Neso asks, '...This is a terrible idea, isn't it?'")
			add_custom_entry( 34, 17, "Anna Neso says, '...I'm... going to check deeper.'")
			add_custom_entry( 34, 24, "You hear the grunting and clanging of a metal ladder being used.")
			add_custom_entry( 35, 1, "You hear the grunting and clanging of a metal ladder being used.")
			add_custom_entry( 35, 25, "Anna Neso says, '...Oh. Wait a minute. Was this... not in the underdark?'")
			add_custom_entry( 35, 38, "Anna Neso says, 'I just... assumed, given the... flesh sounds.'")
			add_custom_entry( 35, 42, "Anna Neso says, '...Test.'")
			add_custom_entry( 35, 49, "You hear the grunting and clanging of a metal ladder being used.")
			add_custom_entry( 36, 4, "Anna Neso says, '...There's a braced airlock, leading out.'")
			add_custom_entry( 36, 11, "Anna Neso says, '...Thankfully, I brought a gun.'")
			add_custom_entry( 36, 54, "Anna Neso says, '...Which I... am definitely not... fumbling with, right now.'")
			add_custom_entry( 37, 27, "Anna Neso says, 'Grunts in frustration as she jams the slugs back into the cylinder.'")
			add_custom_entry( 37, 33, "You hear a gunshot!")
			add_custom_entry( 37, 34, "You hear a gunshot!")
			add_custom_entry( 37, 35, "You hear a gunshot!")
			add_custom_entry( 37, 36, "You hear a gunshot!")
			add_custom_entry( 37, 55, "You hear a gunshot!")
			add_custom_entry( 37, 56, "You hear a gunshot!")
			add_custom_entry( 37, 58, "You hear a gunshot!")
			add_custom_entry( 37, 59, "You hear a gunshot!")
			add_custom_entry( 38, 5, "Anna Neso says, '...RIGHT. Opened.'")
			add_custom_entry( 38, 18, "Anna Neso says, '...I should've brought more ammo.'")
			add_custom_entry( 39, 28, "Anna Neso says, '...Ah. Right. There's the... terraformer housing, again. Nothing else much of note, nearby.'")
			add_custom_entry( 39, 58, "Anna Neso says, '...R-right, I'm... heading back up, now.'")
			add_custom_entry( 40, 0, "You hear the grunting and clanging of a metal ladder being used.")
			add_custom_entry( 40, 11, "Anna Neso says, '...Ah.'")
			add_custom_entry( 40, 17, "Recording stopped.")
			add_custom_entry( 40, 18, "Recording started.")
			add_custom_entry( 40, 44, "Anna Neso says, '...Right. Another crewmember seems to have found their way over. We... talked for a bit, but were interrupted by... it.'")
			add_custom_entry( 41, 21, "Anna Neso says, '...It spoke to me, again. Its call was... different, this time. No asking to become with it. It just... begged for help.'")
			add_custom_entry( 41, 32, "Anna Neso says, '...With what, I am... uncertain.'")
			add_custom_entry( 41, 48, "Stridefast ticks, '....what did you do?'")
			add_custom_entry( 41, 54, "Anna Neso says, '...Before I left to return to record--'")
			add_custom_entry( 41, 55, "Recording stopped.")
			add_custom_entry( 41, 56, "Recording started.")
			add_custom_entry( 42, 04, "Anna Neso asks, '...Right. Now where was I?'")
			add_custom_entry( 42, 47, "Anna Neso says, '...I was... quite rudely interrupted, once again, by my coworker, but... they did have something to make note of, at least.'")
			add_custom_entry( 43, 14, "Anna Neso says, '...Down the ladder, where I'd blown off the brace... there was... gore. Blood and gibs. Smeared all across the flooring.'")
			add_custom_entry( 43, 43, "Anna Neso says, '...They're calling the whole of the crew to Medical, now. I assume we've had another changeling incident.'")
			add_custom_entry( 44, 28, "Anna Neso says, '...Though for now... I think I'll... take the time to investigate a little more, with Stridefast out of the way.'")
			add_custom_entry( 44, 29, "Recording stopped.")
			add_custom_entry( 44, 30, "Recording started.")
			add_custom_entry( 44, 33, "You hear the grunting and clanging of a metal ladder being used.")
			add_custom_entry( 45, 01, "Anna Neso says, '...Nothing near the terraformer housing.'")
			add_custom_entry( 46, 11, "Anna Neso says, '...Nothing in the immediate vicinity, still.'")
			add_custom_entry( 46, 52, "Anna Neso says, '...Hmm. A pair of mesons... likely would've been a boon to me, here.'")
			add_custom_entry( 47, 03, "Anna Neso says, '...Ah. And they're calling for me in specific, now.'")
			add_custom_entry( 47, 10, "Anna Neso says, 'I should... probably head--'")
			add_custom_entry( 47, 32, "Anna Neso says, '...A-ah. The... exist has... sealed behind me, once more.'")
			add_custom_entry( 47, 49, "Anna Neso says, '...Yes, I... think that makes this a... very good time to--'")
			add_custom_entry( 47, 54, "Anna Neso says, 'SHIT.'")
			add_custom_entry( 48, 18, "Anna Neso asks, '...Wait. Is it... not... chasing me?'")
			add_custom_entry( 48, 28, "Anna Neso says, '...A-ah.'")
			add_custom_entry( 48, 40, "Anna Neso says, '...I...'")
			add_custom_entry( 48, 56, "Anna Neso says, '...Presumed, based on prior experience, that, ah...'")
			add_custom_entry( 49, 10, "Anna Neso says, '...T-the... terraformer's... housing. It's--'")
			add_custom_entry( 49, 20, "Anna Neso says, '...It... has opened.'")
			add_custom_entry( 49, 34, "Anna Neso says, '...There's a path inside, from here.'")
			add_custom_entry( 49, 50, "Anna Neso says, '...O-oh, that's...'")
			add_custom_entry( 50, 2, "Anna Neso says, '...This is... not the part of it I'd entered, prior.'")
			add_custom_entry( 50, 56, "Anna Neso asks, '...That... better still be open, when I get back, yeah?'")
			add_custom_entry( 51, 20, "Anna Neso says, '...R-right, ah... in... any case. That is... doubtlessly blood, considering the odor.'")
			add_custom_entry( 51, 31, "Anna Neso says, '...I'm turning on my internals, now.'")
			add_custom_entry( 51, 44, "Anna Neso says, '...We'll... see how well it is to swim through, I... s'pose.'")
			add_custom_entry( 52, 13, "Anna Neso says, '...I... regret not bringing meson goggles, once more.'")
			add_custom_entry( 52, 33, "Anna Neso says, '...Time to follow the stream, then, I... s'pose.'")
			add_custom_entry( 52, 47, "Anna Neso asks, '...Oh, what did I just fuckin' tell you?'")
			add_custom_entry( 52, 50, "Anna Neso, 'Sighs.'")
			add_custom_entry( 53, 15, "Anna Neso says, '...As... long as the place is still marked, I s'pose. That's... maybe a gesture'a good faith.'")
			add_custom_entry( 53, 31, "Anna Neso says, '...Nothing, this way.'")
			add_custom_entry( 53, 37, "Anna Neso says, '...Oh. Or... not.'")
			add_custom_entry( 53, 53, "Anna Neso says, '...Right.'")
			add_custom_entry( 54, 5, "Anna Neso says, '...Gonna... check the other way, first.'")
			add_custom_entry( 54, 24, "Anna Neso says, '...Ah.'")
			add_custom_entry( 54, 26, "Anna Neso, 'Sighs.'")
			add_custom_entry( 54, 42, "Anna Neso says, '...This is likely a terrible idea, but...'")
			add_custom_entry( 55, 1, "Anna Neso says, '...Oh. I... see.'")
			add_custom_entry( 55, 7, "Anna Neso says, '...Right, thank you kindly.'")
			add_custom_entry( 55, 16, "Anna Neso, 'Snaps their fingers.'")
			add_custom_entry( 55, 28, "Anna Neso says, '...Now...'")
			add_custom_entry( 55, 39, "Anna Neso says, '...Right. I'm recording.'")
			add_custom_entry( 55, 56, "Anna Neso says, '...Ah. That's a circle.'")
			add_custom_entry( 56, 29, "Anna Neso asks, '...It... seems a bit more... willing to let me leave, this time. Is that learned behavior, or...?'")
			add_custom_entry( 56, 38, "Anna Neso asks, '...Is this a different entity altogether?'")
			add_custom_entry( 56, 51, "Anna Neso says, '...I... doubt I'll be getting answers to that end, any time soon.'")
			add_custom_entry( 56, 54, "Anna Neso says, '...For now...'")
			add_custom_entry( 57, 29, "Anna Neso says, '...It doesn't seem actively malicious. I... may as well humor th'chance to understand it, even if this all... makes my skin crawl.'")
			add_custom_entry( 57, 46, "Anna Neso says, '...And FOR THE RECORD.'")
			add_custom_entry( 58, 4, "Anna Neso says, 'I have a bomb, so if you think you can--'")
			add_custom_entry( 58, 7, "Anna Neso says, 'G-gah--'")
			add_custom_entry( 58, 36, "Anna Neso asks, '...I... I... see?'")
			add_custom_entry( 58, 44, "Anna Neso says, 'Clears her throat.'")
			add_custom_entry( 59, 15, "Anna Neso says, '...It's... spoken to me. Not in its usual manner, though, that was... no, it wasn't speech, it was something else.'")
			add_custom_entry( 59, 38, "Anna Neso says, '...It's... told me I can... open its... folds of my own accord, now, in... any case.'")
			add_custom_entry( 0, 17, "Anna Neso says, '...Ah.'")
			add_custom_entry( 0, 36, "Anna Neso says, '...That... would seem to be true.'")
			add_custom_entry( 0, 42, "Anna Neso says, '...Right. I... I see.'")
			add_custom_entry( 1, 25, "Anna Neso asks, '...I don't take it that means I should expect you to be any more responsive to questions than usual, then...?'")
			add_custom_entry( 2, 34, "Anna Neso says, '...I s'pose so.'")
			add_custom_entry( 3, 9, "Anna Neso asks, '...A-ah, the... dripping... noise? I don't hear a...?'")
			add_custom_entry( 4, 42, "Anna Neso says, '...I'm... uncertain I've gone the right way.'")
			add_custom_entry( 5, 34, "Anna Neso says, '...Ah. I... where the... steam gathers. I... see.'")
			add_custom_entry( 6, 9, "Anna Neso begins climbing up the lattice.")
			add_custom_entry( 6, 18, "Anna Neso moves up.")
			add_custom_entry( 6, 47, "Anna Neso says, '...RIGHT. Right.'")
			add_custom_entry( 7, 14, "Anna Neso says, '...I've... found a path upward, then. Unexpected. Typically, you'd presume the mysterious head-voice t'urge you deeper, in these kinds of tales.'")
			add_custom_entry( 8, 1, "Anna Neso says, '...Oh. That's... wall reinforcements? Strange to see... construction, in here. Working lights, as well.'")
			add_custom_entry( 8, 44, "Anna Neso asks, '...Ah. The blizzard is even in here, is it?'")
			add_custom_entry( 10, 5, "Anna Neso asks, '...Does it hurt?'")
			add_custom_entry( 10, 39, "Anna Neso asks, '...The... metal-on flesh, the... walls and rods, extruding about everywhere?'")
			add_custom_entry( 13, 28, "Anna Neso says, '...I see. That... tracks, then, I... s'pose. If the company went out of their way to engineer something that pains its way through existence like that, that would be... unusually cruel, even by their standards.'")
			add_custom_entry( 13, 49, "Anna Neso asks, '...What is it you needed my help with, then...?'")
			add_custom_entry( 14, 28, "Anna Neso says, '...Ah. I... see.'")
			add_custom_entry( 15, 24, "Anna Neso says, '...I presumed the voice from the vents... was you, considering the... flesh-chases it typically heralds.'")
			add_custom_entry( 17, 58, "Anna Neso says, '...Unexpectedly amicable, considering how we first met, in... any case.'")
			add_custom_entry( 19, 41, "Anna Neso says, '...Ah. But we have, in a sense, I do believe. I entered it by mistake, some time ago. I was... injured rather severely. They retrieved me in the end, though. Gave me a number'a stern warnings.'")
			add_custom_entry( 22, 44, "Anna Neso says, '...Mmh. Quite, it would seem. So much so, they're not often willing to give as much as information regarding you. That's... sorta how I ended up like that, t'begin with. Didn't realize I even was in the terraformer.'")
			add_custom_entry( 22, 52, "Anna Neso says, 'Chuckles, weakly.'")
			add_custom_entry( 23, 20, "Anna Neso asks, '...D'you have a... name, on that note? Anything you'd prefer to be called?'")
			add_custom_entry( 26, 10, "Anna Neso says, '...I... see. Fair enough, I suppose. It just... seems rather impersonal to refer t'you simply as 'The Terraformer.''")
			add_custom_entry( 26, 22, "Anna Neso says, '...At least while actively holdin' a conversation.'")
			add_custom_entry( 26, 33, "Anna Neso says, '...And, ah... 'critter?''")
			add_custom_entry( 27, 14, "Anna Neso says, '...Who, that... 'Nipper' character? They seem to exist in your vicinity, vaguely.'")
			add_custom_entry( 29, 3, "Anna Neso says, 'I... see. Noted. He... does seem like the type who's scared often, if the drawings are anything to go off of. Not t'say unjustifiably so.'")
			add_custom_entry( 30, 6, "Anna Neso says, '...The drawings he seems t'leave in the maintenance tunnels are actually rather helpful, even t'us. Saved me from stepping on a few landmines, at the least. The... faces are all that confuse me, at present.'")
			add_custom_entry( 30, 40, "Anna Neso asks, '...I... believe I may've seen them drawn near... vents, though, come to think of it? Entrances to the underdark?'")
			add_custom_entry( 30, 52, "Anna Neso asks, '...Does +it+ speak to him as well, then...?'")
			add_custom_entry( 32, 21, "Anna Neso says, 'Lets out a soft snort. '...Kindred spirits, then, I... s'pose. I'll have to see about finding a conversation with him, sometime. It seems like it would be... valuable, for research purposes.'")
			add_custom_entry( 33, 28, "Anna Neso says, '...Hmm. Maybe I should see about heading home, soon, though. They've... been expecting me back for a test, now, for a while, and I'd... like to leave myself time to hide my tape 'n get a backup scan, in case they opt for extreme measures.'")
			add_custom_entry( 36, 20, "Nipper moves down.")
			add_custom_entry( 36, 26, "Anna Neso says, '...Ah-'")
			add_custom_entry( 36, 54, "Nipper creels, 'Alkao bomen muvent...'")
			add_custom_entry( 36, 58, "Anna Neso asks, '...Right. Ah... Nipper, then, I... presume?'")
			add_custom_entry( 36, 58, "Nipper creels, 'Niu terhin bar duobao...'")
			add_custom_entry( 37, 11, "Anna Neso says, '...Ah. You... don't speak common, I presume. Right.'")
			add_custom_entry( 38, 27, "Anna Neso says, '...Ah.'")
			add_custom_entry( 38, 29, "Anna Neso, 'Snaps their fingers.'")
			add_custom_entry( 44, 44, "Anna Neso, 'Snaps their fingers.'")
			add_custom_entry( 49, 21, "Anna Neso, 'Snaps their fingers.'")
			add_custom_entry( 49, 23, "Nipper begins climbing up the lattice.")
			add_custom_entry( 49, 32, "Anna Neso says, '...Ah.'")
			add_custom_entry( 49, 33, "Anna Neso begins climbing up the lattice.")
			add_custom_entry( 49, 41, "Anna Neso moves up.")
			add_custom_entry( 50, 34, "Anna Neso moves down.")
			add_custom_entry( 50, 45, "Nipper moves down.")
			add_custom_entry( 50, 48, "Nipper begins climbing up the lattice.")
			add_custom_entry( 50, 49, "Anna Neso says, 'Ah-'")
			add_custom_entry( 50, 58, "Anna Neso begins climbing up the lattice.")
			add_custom_entry( 50, 58, "Anna Neso begins climbing up the lattice.")
			add_custom_entry( 51, 06, "Anna Neso moves up.")
			add_custom_entry( 51, 23, "Anna Neso, 'Screams!'")
			add_custom_entry( 51, 23, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 51, 23, "Anna Neso, 'Screams!'")
			add_custom_entry( 51, 29, "Anna Neso, 'Screams!'")
			add_custom_entry( 51, 29, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 51, 29, "Anna Neso, 'Screams!'")
			add_custom_entry( 51, 29, "Anna Neso, 'Screams!'")
			add_custom_entry( 51, 29, "Anna Neso stammers, 'G-G-G-GAH-H-H-H-'")
			add_custom_entry( 51, 35, "Anna Neso stammers, 'F-F-F-F-FUCK--'")
			add_custom_entry( 51, 38, "Anna Neso stutters, 'N-NOT-T AG-GAIN-N-'")
			add_custom_entry( 51, 42, "Anna Neso stutters, 'Ag-gh-h-hk-k...'")
			add_custom_entry( 51, 44, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 51, 48, "Anna Neso stammers, '...B-B-bu...'")
			add_custom_entry( 51, 54, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 52, 16, "Anna Neso stammers, '...G-G-g-g-g-guh, ah-h-h-h... -sh-h-h-hit, h-here, uh-h-h-hm-m--'")
			add_custom_entry( 52, 18, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 52, 22, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 52, 28, "Anna Neso stutters, '...G-G-g-gah-h...'")
			add_custom_entry( 52, 34, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 52, 35, "Nipper moves down.")
			add_custom_entry( 52, 47, "Nipper begins climbing up the lattice.")
			add_custom_entry( 52, 55, "Nipper moves up.")
			add_custom_entry( 52, 55, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 53, 14, "Anna Neso stammers, '...G-G-Guh-h...'")
			add_custom_entry( 53, 22, "Nipper begins climbing up the lattice.")
			add_custom_entry( 53, 23, "Anna Neso stutters, 'C-Can-n... h-h-h-har-r-r-rd-dl-l-ly s-see s-st-tr-r-raig-gh-ht-t...'")
			add_custom_entry( 53, 30, "Nipper begins climbing up the lattice.")
			add_custom_entry( 53, 39, "Nipper moves up.")
			add_custom_entry( 54, 11, "Anna Neso stammers, '...h-hat... t-th-hat t-th-hr-row-ws... a w-wr-ren-n-n-nch-h in-n t-th-he w-wor-rk-ks-s, f-fo cer-rtain-n...'")
			add_custom_entry( 54, 27, "Anna Neso, 'Groans!'")
			add_custom_entry( 54, 58, "Anna Neso says, '...Gah.'")
			add_custom_entry( 55, 34, "Anna Neso asks, '...I am? Shit, I swear I turned those off?'")
			add_custom_entry( 55, 48, "Anna Neso says, '...A-ah--'")
			add_custom_entry( 55, 53, "Anna Neso says, '...Right.'")
			add_custom_entry( 56, 25, "Nipper moves down.")
			add_custom_entry( 56, 59, "Anna Neso says, '...Gwegh... right. This is looking... a little more familiar, now.'")
			add_custom_entry( 57, 21, "Anna Neso says, '...RIGHT. There we are.'")
			add_custom_entry( 57, 29, "Anna Neso says, 'Lets out a deep exhale.'")
			add_custom_entry( 57, 31, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 57, 48, "Anna Neso says, '...There we... +aghk.+'")
			add_custom_entry( 57, 59, "Anna Neso says, '...RIGHT. Right, ah... thank you kindly.'")
			add_custom_entry( 58, 3, "Anna Neso, 'Snaps her fingers.'")
			add_custom_entry( 58, 4, "Medibot beeps, 'Hey, Anna Neso! Hold on, I'm coming.'")
			add_custom_entry( 58, 38, "Ca-Clunk")
			add_custom_entry( 58, 59, "Anna Neso, 'Yells in pain!'")
			add_custom_entry( 59, 12, "Recording stopped.")
			add_custom_entry( 59, 13, "Recording started.")
			add_custom_entry( 59, 29, "Anna Neso says, 'P-pressed for time, but... a valve caught me. Dialogue with Nipper was enlightening, but... not so much as I'd hoped. E-end... log.'")
			add_custom_entry( 59, 30, "Recording stopped.")

		if(14)
			add_custom_entry( 0, 8, "Recording started.")
			add_custom_entry( 0, 20, "Anna Neso says, 'This is Anna Neso, Xenoarchaeologist. The date is 2569-10-18.")
			add_custom_entry( 0, 37, "Anna Neso says, 'I have discovered a spellbook. I have become capable of blasting ass.")
			add_custom_entry( 0, 43, "Anna Neso says, 'That is all.")
			add_custom_entry( 0, 47, "Anna Neso says, 'End log.")
			add_custom_entry( 0, 49, "Recording stopped.")

		if(15)
			add_custom_entry( 0, 50, "Recording started.")
			add_custom_entry( 1, 33, "Anna Neso says, 'Resume log, actually. I've been left with a burning desire for more spells. I'm... going to see if there are any more, secreted around. I'm sure this is a very great idea, and not hubris on my part.")
			add_custom_entry( 1, 34, "Recording stopped.")

		if(16)
			add_custom_entry( 0, 7, "Recording started.")
			add_custom_entry( 0, 32, "Stridefast gives out a cog rattling sigh. 'Least that stone will remain lost in this dimension for now. Just a matter of-'")
			add_custom_entry( 0, 49, "Stridefast: 'What is that NOISE?!'")
			add_custom_entry( 1, 19, "Stridefast: 'Hopefully I don't ever enounter whatever that...thing was making that racket.'")
			add_custom_entry( 1, 28, "Stridefast: 'I really should leave....but...part of me feels ot- oh...it's gone'")
			add_custom_entry( 2, 12, "Stridefast: 'COGS ABOVE-'")
			add_custom_entry( 2, 20, "Stridefast: 'THIS PLACE IS REALLY HELL...'")
			add_custom_entry( 4, 14, "Stridefast gives out a rattling sigh once more, stomping about for a while before the noises become *squishier* sounding as walks off metal onto flesh. 'This place is...very similar to back at the outpost...almost a copy though theres definately...different parts...I wonder if accesses are the same...going to see if I can find engineering.'")
			add_custom_entry( 4, 19, "Stridefast: 'Though my inhibitors keeping my emotions in check when I don't want them....I can feel the heat from it working over time...'")
			add_custom_entry( 5, 26, "Stridefast: 'I've found engineering....and seems even here...the creatures that inhabit the place fight amongst themselves...'")
			add_custom_entry( 5, 32, "Stridefast: 'Access does seem to carry between the dimensions too...'")
			add_custom_entry( 5, 41, "Stridefast: 'Cogs above the hell was that thing?!'")
			add_custom_entry( 6, 4, "Stridefast: 'I need to get out of here- my inhibitor is goign to melt down at this rate...'")
			add_custom_entry( 7, 44, "Stridefast: 'What the-'")
			add_custom_entry( 7, 56, "Stridefast: 'Hey can someone let me out? I'm in....the recovery room?'")
			add_custom_entry( 7, 59, "Recording stopped.")

		if(17)
			add_progressive("We know what you did.")

		if(18)
			add_progressive("You failed them all.")
			if(prob(20))
				add_progressive("You let them die.")

		if(19)
			add_progressive("You let them die.")
			if(prob(20))
				add_progressive("You failed them all.")
*/
