// Heavily modified port of https://github.com/Bubberstation/Bubberstation/blob/b6dbca4ef6bbf4601b8e752176376166025c8d60/modular_zubbers/code/modules/blooper/bark_list.dm
// Bubbers uses actual voice datums! We uses ugly global lists inside another assoc list. This felt sinful to make.

/datum/controller/subsystem/sounds/create_talk_sound_map()
	. = ..() // Extend the base sounds!
	talk_sound_map["Vox Shriek"] = list('sound/voice/shriek1.ogg')
	// Bubbers base
	talk_sound_map["Muted String (Low)"] = list('sound/runtime/instruments/synthesis_samples/guitar/crisis_muted/C2.ogg')
	talk_sound_map["Muted String (Medium)"] = list('sound/runtime/instruments/synthesis_samples/guitar/crisis_muted/C3.ogg')
	talk_sound_map["Muted String (High)"] = list('sound/runtime/instruments/synthesis_samples/guitar/crisis_muted/C4.ogg')
	talk_sound_map["Banjo (Medium)"] = list('sound/runtime/instruments/banjo/Cn3.ogg')
	talk_sound_map["Banjo (High)"] = list('sound/runtime/instruments/banjo/Cn4.ogg')
	talk_sound_map["Squeaky"] = list('modular_zubbers/sound/items/toy_squeak/toysqueak1.ogg')
	talk_sound_map["Chittery"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/chitter.ogg')
	talk_sound_map["Synthetic (Grunt)"] = list('sound/misc/bloop.ogg')
	talk_sound_map["Synthetic (Normal)"] = list('modular_zubbers/sound/machines/uplink/uplinkerror.ogg')
	talk_sound_map["Windy"] = list('modular_zubbers/sound/items/weapons/bulletflyby.ogg')
	talk_sound_map["Brassy"] = list('modular_zubbers/sound/machines/clockcult/integration_cog_install.ogg')
	talk_sound_map["Moff squeak"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/mothsqueak.ogg')
	talk_sound_map["Meow"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/meow1.ogg')
	talk_sound_map["Chirp"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/chirp.ogg')
	talk_sound_map["Caw"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/caw.ogg')
	// Undertale
	talk_sound_map["Alphys"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_alphys.ogg')
	talk_sound_map["Asgore"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_asgore.ogg')
	talk_sound_map["Flowey (normal)"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_flowey_1.ogg')
	talk_sound_map["Flowey (evil)"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_flowey_2.ogg')
	talk_sound_map["Papyrus"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_papyrus.ogg')
	talk_sound_map["Ralsei"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_ralsei.ogg')
	talk_sound_map["Sans"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_sans.ogg')
	talk_sound_map["Toriel"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_toriel.ogg')
	talk_sound_map["Undyne"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_undyne.ogg')
	talk_sound_map["Temmie"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_temmie.ogg')
	talk_sound_map["Susie"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_susie.ogg')
	talk_sound_map["Gaster"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_gaster_1.ogg')
	talk_sound_map["Mettaton"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_metta_1.ogg')
	talk_sound_map["Generic Monster 1"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_monster1.ogg')
	talk_sound_map["Generic Monster 2"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/undertale/voice_monster2.ogg')
	// Don't starve
	talk_sound_map["Wilson"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wilson_blooper.ogg')
	talk_sound_map["Wolfgang"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wolfgang_blooper.ogg')
	talk_sound_map["Woodie"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/woodie_blooper.ogg')
	talk_sound_map["Wurt"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wurt_blooper.ogg')
	talk_sound_map["wx78"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/dont_starve/wx78_blooper.ogg')
	// Kazooie
	talk_sound_map["Whistle 1"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/birdwhistle.ogg')
	talk_sound_map["Whistle 2"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/birdwhistle2.ogg')
	talk_sound_map["Chittery Alt"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/moth/mothchitter2.ogg')
	talk_sound_map["Caw 2"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/caw.ogg')
	talk_sound_map["Caw 3"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/caw2.ogg')
	talk_sound_map["Caw 4"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/caw3.ogg')
	talk_sound_map["Ehh 1"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh.ogg')
	talk_sound_map["Ehh 2"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh2.ogg')
	talk_sound_map["Ehh 3"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh3.ogg')
	talk_sound_map["Ehh 4"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh4.ogg')
	talk_sound_map["Ehh 5"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ehh5.ogg')
	talk_sound_map["Faucet 1"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/faucet.ogg')
	talk_sound_map["Faucet 2"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/faucet2.ogg')
	talk_sound_map["Ribbit"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/ribbit.ogg')
	talk_sound_map["Hoot"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/hoot.ogg')
	talk_sound_map["Tweet"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/tweet.ogg')
	talk_sound_map["Dwoop"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/dwoop.ogg')
	talk_sound_map["Uhm"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/uhm.ogg')
	talk_sound_map["Wurtesh"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/wurble1.ogg')
	talk_sound_map["Chitter2"] = list('modular_zubbers/code/modules/blooper/voice/bloopers/kazooie/chitter1.ogg')
